config/routes.rb
Rails.application.routes.draw do
  get 'contacts' => 'contacts#index', as: 'contacts_index'
  match 'contacts/confirm' ,:via => :post
  match 'contacts/create' ,:via => :post
  root 'pages#index'
  get 'about' => 'pages#about', as: 'pages_about'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => "お名前を入力してください"}
  validates :email, :presence => {:message => "メールアドレスを入力してください"}
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/ ,:message => "メールアドレスをご確認ください"
  validates :message, :presence => {:message => "お問い合わせ内容を入力してください"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.new
    render :action => 'index'
  end

  def confirm
    @contact = Contact.new(contact_params)

    if @contact.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def create
    @contact = Contact.new(contact_params)

    if params['back']
      render :action => 'index'
    else 
      begin
        @contact = Contact.new(contact_params)
        UserMailer.contact_form(@contact).deliver
        flash.now[:error] = nil
        render :action => 'create'
      rescue Net::SMTPAuthenticationError, Net::SMTPServerBusy, Net::SMTPSyntaxError, Net::SMTPFatalError, Net::SMTPUnknownError => e
        flash[:error] = "送信できませんでした。にご連絡ください。"
      end
    end
  end

  private
    def contact_params
     params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/confirm.html.erb
<% provide :title ,"お問い合わせ" %>
<% provide :contact_active ,"active" %>

<div class="container">
  <div class="h1">お問い合わせ</div>
  <p class="lead">入力内容をご確認ください</p>

  <%= form_for @contact,:url => contacts_create_path,:html => {:class => 'contact_form'} do |f| %>

    <dl class="row">
      <dt class="col-sm-12"><%= f.label :name, "お名前" %></dt>
      <dd class="col-sm-12"><%= @contact.name %><%= f.hidden_field :name, class: "form-group　form-control" %></dd>
      <dt class="col-sm-12"><%= f.label :email, "メールアドレス（半角）" %></dt>
      <dd class="col-sm-12"><%= @contact.email %><%= f.hidden_field :email, class: "form-group　form-control" %></dd>
      <dt class="col-sm-12"><%= f.label :message, "お問い合わせ内容" %></dt>
      <dd class="col-sm-12"><%= @contact.message %><%= f.hidden_field :message, class: "form-group　form-control" %></dd>
    </dl>
    <p class="col-sm-12">
      <%= f.submit "戻る", name: "back", class: "btn btn-secondary btn-back" %>
      <%= f.submit "この内容で送信する", class: "btn btn-primary" %>
    </p>
  <% end %>

</div>

app/views/contacts/create.html.erb
<% provide :title ,"お問い合わせ" %>
<% provide :contact_active ,"active" %>

<div class="container">
  <div class="h1">お問い合わせ</div>
  <p class="lead">お問い合わせを承りました。ありがとうございました。</p>
</div>

app/views/contacts/index.html.erb
<% provide :title ,"お問い合わせ" %>
<% provide :contact_active ,"active" %>

<div class="container">
  <div class="h1">お問い合わせ</div>
  <p class="lead">ご覧いただきありがとうございます。不明点ございましたら、どうぞお気軽にお問い合わせください。</p>

  <div class="container">

  <%= form_for @contact,:url => contacts_confirm_path,:html => {:class => 'contact_form'} do |f| %>

    <% if @contact.errors.any? %>
    <div class="alert alert-danger">
      <strong　class="alert-heading">入力内容をご確認ください</strong>
        <ul>
        <% @contact.errors.each do |attr,msg| %>
          <li class="alert-link"><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <dl class="row">
      <dt class="col-sm-12"><%= f.label :name, "お名前" %></dt>
      <dd class="col-sm-12"><%= f.text_field :name, require: true, class: "form-group form-control" %></dd>
      <dt class="col-sm-12"><%= f.label :email, "メールアドレス（半角）" %></dt>
      <dd class="col-sm-12"><%= f.text_field :email, require: true, class: "form-group form-control" %></dd>
      <dt class="col-sm-12"><%= f.label :message, "お問い合わせ内容" %></dt>
      <dd class="col-sm-12"><%= f.text_area :message, require: true, class: "form-group form-control" %></dd>
    </dl>
    <p class="col-sm-12 text-center"><%= f.submit "この内容で送信する",class: "btn btn-primary" %></p>
  <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted">&copy; <%= Time.now.year %> Site Name</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
    <a class="navbar-brand" href="/">Site Name</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars" aria-controls="navbars" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbars">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Site Nameについて", pages_about_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to "お問い合わせ", contacts_index_path, class: "nav-link #{yield(:contact_active)}" %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Site Name</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %>">
    <%= render partial:"layouts/header"%>
    <%= yield %>
    <%= render partial:"layouts/footer"%>
  </body>
</html>

app/views/pages/about.html.erb
<% provide :title ,"Site Nameについて" %>
<% provide :about_active ,"active" %>

  <div class="container">
    <div class="h1">Site Nameについて</div>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit, fugiat corporis reiciendis velit mollitia, expedita consequuntur! Optio asperiores amet accusantium magni, qui quasi aspernatur placeat minus quis ratione, autem nulla.</p>

  </div>

app/views/pages/index.html.erb
<% provide :title ,"Home" %>

<div class="top-img">
  <h1 class="lead">Site Nameの説明</h1>
</div>
<div class="container">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
     </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
    </div>

    <hr>

    <div class="row">
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
     </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div>
    </div>
  </div>
</div>